import type { Metadata } from "next";
import "./globals.css";
import { FilterProvider } from "./_context/filterContext";
import { StatsProvider } from "./_context/stats";
import { Toaster } from "react-hot-toast";
import QueryProvider from "./_context/queryProvider";
import { Suspense } from "react";
import Loader from "./_components/Loader";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body>
				<Suspense fallback={<Loader />}>
					<FilterProvider>
						<QueryProvider>
							<StatsProvider>{children}</StatsProvider>
						</QueryProvider>
					</FilterProvider>
				</Suspense>
				<Toaster />
			</body>
		</html>
	);
}
